### ISSUE TITLE
Custom rescripts receive no parameters

### ISSUE THREAD

**Issue by szdc** [rescripts/rescripts#1]
I'm trying to transform my webpack config (after creating a standard CRA2 app) following the [structure from the README](https://github.com/rescripts/rescripts#rescript-structure) but the first parameter (which I assume is meant to be the webpack config) is `undefined`.  

Here's a trivial example of my `.rescriptsrc` file:
```js
module.exports = [
  [(config) => {
    console.log(config);
    return config;
  }]
];
```

Expected output:
```js
{
  mode: 'development',
  devtool: 'cheap-module-source-map',
  ...
}
```

Actual output:
```
undefined
```

Am I doing something wrong?

I was specifically trying to follow the `a function that takes in and returns a webpack config` section.  Moving the function to a file like in the example (obviously) has no effect either.

**Comment by szdc** [comment]
Looking at some of the examples underneath show that you may have to pass in a function that returns a function that takes in the arguments, which does work.  So, in my case where my rescript doesn't take any arguments, that looks like:
```js
module.exports = [
  [() => config => {
    console.log(config);
    return config;
  }]
];
```

This is reinforced by some examples but not others.  Thoughts?

**Comment by harrysolovay** [comment]
Hi @szdc –– If you're using a `.rescriptsrc` file with no '.js' extension, NodeJS won't execute it as JS (so the array of rescripts, which contains the webpack-transforming function, won't be exported). Also, wrapping that function in braces will throw an error (when wrapped in braces, latter elements are expected (they get passed into the rescript)). Please let me know if the first way you wrote it doesn't work with a '.js' extension.

**Comment by harrysolovay** [comment]
Oh whoops: I see you wrapped it in braces up top as well. Try this:

```js
module.exports = (config) => {
  console.log(config);
  return config;
};
```

Or like this if you plan to add more rescripts:

```js
module.exports = [
  (config) => {
    console.log(config);
    return config;
  }
];
```

**Comment by szdc** [comment]
Ah my bad, I was mistakenly wrapping the rescript I was defining in another array.  Thanks! :smile:

**Comment by harrysolovay** [comment]
@szdc no problem. Thanks for using Rescripts & let me know if you have any more problems :)
