### ISSUE TITLE
Trouble installing @rescripts/rescript-use-babel-config

### ISSUE THREAD

**Issue by jackpope** [rescripts/rescripts#11]
We need to add the emotion babel plugin to `react-scripts test`. The project's current .babelrc works fine for builds, but when used with `rescripts test`, it doesn't seem to be applied. 

Running rescripts packages and react-scripts on latest versions. I did the following:

1. Installed packages `@rescripts/cli` and `@rescripts/rescript-use-babel-config`
2. Added package.json config: `"rescripts": [["use-babel-config", ".babelrc"]]`
3. Run `rescripts test`

The error is related to the emotion component selector syntax, meaning the babel plugin is not in use. There are no errors or logs regarding the rescripts usage. Are there some ways to debug this package and see if the config is being applied or not?

**Comment by harrysolovay** [comment]
Hi @jackpope –– your usage is correct, but it doesn't apply to the `test` script. You'll likely want to edit the jest configuration by using a `.rescriptsrc.js` file.

Once you've deleted the `rescripts` field from your `package.json`, create a root-level `.rescriptsrc.js` file:

```js
module.exports = [
  ['use-babel-config', '.babelrc'],
  {
    jest: config => {
      // override jest transpilation config
      return updatedConfig
    }
  }
]
```

If you'd rather not override the Jest config, you could use use [@babel/register](https://babeljs.io/docs/en/babel-register) to fly-compile your tests. There's a slight delay on first run, but it's pretty solid in development.

Please let me know how it pans out. Happy to provide more support if needed :)

**Comment by jackpope** [comment]
Hey @harrysolovay thanks for the quick and thoughtful response. I'm curious, is rescripts config not applied to the `test` command by design or has it not been implemented yet?

I tried to use the `@babel/register` package inline as I've done with Mocha in the past but unfortunately jest doesn't respect `--require` so I can't do `react-scripts test --require @babel/register`

I was able to get the tests running by using your suggested `.rescriptsrc.js` method. Mine looks like this:

```javascript
module.exports = [
  ['use-babel-config', '.babelrc'],
  {
    jest: config => {
      // react-scripts provides a transformer file in the jest config here
      // changing it to 'babel-jest' will look for a root .babelrc by default
      config.transform['^.+\\.(js|jsx|ts|tsx)$'] = 'babel-jest';
      return config
    }
  }
];
```

**Comment by harrysolovay** [comment]
Glad to hear you were able to get it working. The `@rescripts/rescript-use-babel-config` package doesn't yet apply the config to Jest––this is certainly on my todo list. The good news is, that update shouldn't be breaking (although you'll probably want to revert your config back to what it was initially once I've merged). Sorry for the inconvenience!

**Comment by harrysolovay** [comment]
Oh and, @jackpope –– I'll ping you as soon as it's ready

**Comment by yuritoledo** [comment]
Any news? Even with https://github.com/harrysolovay/rescripts/issues/11#issuecomment-451161636 this config, yet it doesnt work :/

**Comment by harrysolovay** [comment]
@yuritoledo thank you for the reminder. I believe I grew complacent in anticipation of `RomeJS` (the upcoming "Babel replacement" / bundler / testing framework being built by the creator of Babel and used internally at Facebook). `RomeJS` will certainly inform new versions of `CRA` (I don't know how soon). To avoid the workaround above would require patching Jest (in addition to `react-scripts`)... which I'm not against. That being said, it's probably further down on my todo list, as I don't believe this impairs users' productivity, and I expect CRA to change. Would rather wait for the next big release before reworking `rescripts`... unless, has the workaround above broken? I wanna make sure your use case is covered.
