### ISSUE TITLE
How to add 'externals' setting

### ISSUE THREAD

**Issue by kxoo** [rescripts/rescripts#12]
### Hi,  I try to add 'externals'

> 　externals: {
> 　　AMap: 'AMap',
>　}

result is 

> TypeError: reduce: list must be array or iterable

### here is my problem code

.rescriptsrc.js

```
const {edit, getPaths} = require('@rescripts/utilities')

const matcher = inQuestion => 
  inQuestion.externals && inQuestion.externals.AMap

const transform = match => ({
  ...match,
  externals: {
    ...match.externals,
    AMap : 'AMap'
  },
})
module.exports = config => edit(
   ['use-babel-config', '.babelrc.json'],
   transform,
   getPaths(matcher, config),
   config
)
```
#### before i did it  everything is ok

.rescriptsrc.js

```
module.exports =  [
  ['use-babel-config', '.babelrc.json'],
 ]

```
babelrc.json

```

{
  "presets": [
    "react-app"
  ],
  "plugins": [
    [
      "@babel/plugin-proposal-decorators",
      {
        "legacy": true
      }
    ]
  ]
}

```

### Look like i still not code it right 🧐🧐🧐

**Comment by harrysolovay** [comment]
Hi @kxoo –– here's your problem:

```js
module.exports = config => edit(
   ['use-babel-config', '.babelrc.json'],
   transform,
   getPaths(matcher, config),
   config
)
```

Should be...

```js
module.exports = [
  ['use-babel-config', '.babelrc.json'],
  config => edit(
    transform,
    getPaths(matcher, config),
    config
  )
]
```

**Comment by harrysolovay** [comment]
@kxoo are you sure that the module is installed? Can you try resolving the `AMap` module with `require.resolve`? Also, I might be able to help out better if I could take a look at the "AMap" docs –– please point me to where I can check out this module :)

**Comment by kxoo** [comment]
@harrysolovay I installed it in ' index.html ' with

>  <script src="https://webapi.amap.com/maps?v=1.4.12&key=KEY"></script>

and that doc is Chinese

> https://lbs.amap.com/api/javascript-api/guide/abc/load

one thing you maybe need to know, i can use 'AMap' with ' window.AMap'

**Comment by kxoo** [comment]
@harrysolovay yes, I realized that I need add `externals` object not matched .  It looks like I needn't use `getPaths` , but I can't find the way in the `readme`,  can you add an example on `readme` or here . 
and very thanks for your did and help. 🌟🌟🌟

**Comment by harrysolovay** [comment]
@kxoo the `@rescripts/utilities` package is a collection of helpers for more complex use cases. Given that the `externals` field is 1-level deep, I'd recommend directly manipulating the config. It should be as simple as doing this:

```js
module.exports = [
  ['use-babel-config', '.babelrc.json'],
  config => ({
    ...config,
    externals: {
      AMap: 'AMap'
    },
  })
]
```

**Comment by kxoo** [comment]
Sooooo good! it works! thx your help again! 🎆🎇🎆
