### ISSUE TITLE
[Question] Stacking `use-babel-config`

### ISSUE THREAD

**Issue by d3dc** [rescripts/rescripts#14]
Let's say I have some customized package of rescripts: `my-rescripts` with an internal `use-babel-config` and some internal source (not 'package' or '.babelrc').

If I then also want to use a `.babelrc` in a project using `my-rescripts`, how would I go about configuring this?

Naively, I thought:
```
[
  ['my-rescript'],
  ['use-babel-config', '.babelrc']
]
```

[but from reading the source](https://github.com/rescripts/rescripts/blob/master/packages/rescripts/use-babel-config/index.js#L29) it looks like [`presets` and `plugins` will be reset for every use](https://github.com/rescripts/rescripts/blob/master/packages/rescripts/use-babel-config/index.js#L41).

**Comment by harrysolovay** [comment]
Hi @d3dc –– You are correct. Rescripts are applied top-down depth-first... so any babel-adjusting rescripts inside of `my-rescript` will be overriden by ```js['use-babel-config', '.babelrc']```. The design of `@rescripts/rescript-use-babel-config` is such that there is a single source of truth for your Babel configuration. This doesn't mean that you can't modularize your Babel config... it just means that you should be careful not to override it.

One other thing I want to point out is that you're not passing arguments to `my-rescripts`... so you can adjust your code to this:

```diff
[
- ['my-rescripts'],
+ 'my-rescripts',
  ['use-babel-config', '.babelrc']
]
```

Please let me know if this doesn't answer your question, and I'll try again ahaha. Let me know how I can help :)

**Comment by harrysolovay** [comment]
You could do this:

```js
module.exports = babelConfigPath => ([
  'my-rescripts',
  ['use-babel-config', babelConfigPath]
])
```

Also, the rescript loader checks absolute, root-relative and node_module-relative paths (thought that might be useful, incase yours is an issue of resolving the configuration)

**Comment by harrysolovay** [comment]
@d3dc can this issue be closed?
