### ISSUE TITLE
Please help. Give an example how to add loader to Webpack.

### ISSUE THREAD

**Issue by dachinat** [rescripts/rescripts#5]
Hello. Can you please give an example of adding a loader? I couldnot find it in your examples.

For example `raw-loader` needs something like this

```
module: {
    rules: [
      {
        test: /\.txt$/,
        use: 'raw-loader'
      }
    ]
  }
```

Thanks.

**Comment by harrysolovay** [comment]
You could solve this problem quick and dirty like this:

`.rescriptsrc.js`

```js
module.exports = config => {
  config.modules.rules.unshift({
    test: /\.txt$/,
    use: 'raw-loader'
  })
  return config
}
```

Since you're adding rules (a simpler operation on the config), it's safe to say that near-term future versions of `react-scripts` will NOT break the code above. In most cases, however, you'll want to write a matcher and transform, and then use the `@rescripts/utilities` helpers (this will target portions of the config dynamically and make your code more future-proof). Here's how you would use it in this situation:

`.rescriptsrc.js`

```js
const {edit, getPaths} = require('@rescripts/utilities')

const matcher = inQuestion =>
  inQuestion.module && inQuestion.module.rules

const transform = match => ({
  ...match,
  module: {
    ...match.module,
    rules: [
      {
        test: /\.txt$/,
        use: 'raw-loader',
      },
      ...match.module.rules,
    ],
  },
})

module.exports = config => edit(
  transform,
  getPaths(matcher, config),
  config,
)
```

**Comment by dachinat** [comment]
@harrysolovay thanks a lot, I'll be looking in this project.

**Comment by kxoo** [comment]
Sry, too difficult to understand.
I want to  change CSS modules in React,  and confused should i select 'editWebpackPlugin' or 'config.modules.rules.unshift' ?

```

{
  test: /\.css$/,
  use: [
    require.resolve('style-loader'),
    {
      loader: require.resolve('css-loader'),
      options: {
        importLoaders: 1,
        modules: true
      }
    }
  ]
}
```

### And it's nest ...

**Comment by harrysolovay** [comment]
Hi @kxoo –– CSS module support in Webpack isn't a plugin, it's a loader. For this reason, you'll need to use `getPaths` and `edit` from `@rescripts/utilities`.

`.rescriptsrc.js`

```js
const {edit, getPaths} = require('@rescripts/utilities')

const matcher = inQuestion =>
  inQuestion.test === /\.module\.css$/ || inQuestion.test === /\.module\.(scss|sass)$/

const transform = match => {
  // edit and return the updated loader
}

module.exports = config => edit(
  transform,
  getPaths(matcher, config),
  config,
)
```

Inside of your `transform` function, try first logging out the config portions that it takes in to make sure that it is targeting CSS/SASS module loaders correctly. Please let me know how this goes :)

**Comment by kxoo** [comment]
Hi, @harrysolovay ,according to your reply i realized that create-react-app is support css-module by using ' xxx.module.css'  so i didn't change anything, and i still like this repo so much. its very useful. thx for your help and did !

**Comment by harrysolovay** [comment]
No problem @kxoo — one thing that you still might find useful is @rescripts/rescript-use-stylelint — Incase you’d like to define linting for your css modules 👍
