### ISSUE TITLE
CRA 2.1.2 merged webpack dev/prod config files

### ISSUE THREAD

**Issue by liyuanqiu** [rescripts/rescripts#8]
See this PR: [#5722](https://github.com/facebook/create-react-app/pull/5722/files)

Although it is an internal change of CRA 2.1.2, really a breaking change to users of rescripts.

I've submitted a PR: [#7](https://github.com/rescripts/rescripts/pull/7) to adopt this change.

If you want to support all versions of CRA 2, you shouldn't accept my PR because it just works with CRA 2.1.2

**Comment by harrysolovay** [comment]
Thanks @liyuanqiu for your help spotting this breaking change. Just added a note about react-scripts@^2.1.2 compatibility in the readme. Closing this issue :)
